-- 코드를 입력하세요
SELECT b.AUTHOR_ID, a.AUTHOR_NAME, b.CATEGORY, SUM(b.PRICE * bs.SALES) as TOTAL_SALES
FROM BOOK as b
JOIN BOOK_SALES as bs
ON b.BOOK_ID = bs.BOOK_ID 
JOIN AUTHOR as a ON b.AUTHOR_ID = a.AUTHOR_ID
WHERE bs.SALES_DATE like '2022-01%'
GROUP BY b.AUTHOR_ID, b.CATEGORY
ORDER BY b.AUTHOR_ID ASC, b.CATEGORY DESC