SELECT c.CAR_ID, c.CAR_TYPE, ROUND(c.DAILY_FEE * 30 * (100 - d.DISCOUNT_RATE)/100) as FEE
FROM CAR_RENTAL_COMPANY_CAR as c
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN as d ON c.CAR_TYPE = d.CAR_TYPE
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY as h ON c.CAR_ID = h.CAR_ID
WHERE c.CAR_ID NOT IN (
    SELECT DISTINCT(CAR_ID)
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE END_DATE >= '2022-11-01' AND START_DATE <= '2022-12-01'
) and d.DURATION_TYPE like '30%'
and c.CAR_TYPE IN ('세단', 'SUV')
GROUP BY c.CAR_ID
HAVING (FEE >= 500000 AND FEE < 2000000) 
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC