-- 코드를 입력하세요
SELECT US.USER_ID, US.NICKNAME, CONCAT(US.CITY, " ", US.STREET_ADDRESS1, " ", US.STREET_ADDRESS2) as 전체주소, 
CONCAT(SUBSTRING(US.TLNO, 1, 3), '-', SUBSTRING(US.TLNO, 4, 4), '-', SUBSTRING(US.TLNO, 8)) AS 전화번호
FROM USED_GOODS_USER as US
JOIN USED_GOODS_BOARD as GB
ON GB.WRITER_ID = US.USER_ID
GROUP BY US.USER_ID
       HAVING COUNT(GB.WRITER_ID) >= 3
       ORDER BY US.USER_ID DESC