-- 코드를 입력하세요
SELECT YEAR(SALES_DATE) as YEAR, 
MONTH(SALES_DATE) as MONTH, 
COUNT(DISTINCT(u.USER_ID)) as PURCHASED_USRS, 
ROUND(COUNT(DISTINCT u.USER_ID) / (SELECT COUNT(*) FROM USER_INFO WHERE JOINED LIKE '2021%'), 1) as PURCHASED_RATIO
FROM USER_INFO as u
JOIN ONLINE_SALE as o
ON u.USER_ID = o.USER_ID
WHERE u.JOINED LIKE '2021%'
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH