WITH APRIL_APPOINTMENT as (
    SELECT APNT_YMD, APNT_NO, PT_NO, MCDP_CD, MDDR_ID
    FROM APPOINTMENT
    WHERE APNT_CNCL_YN = "N" and APNT_YMD LIKE "2022-04-13%"
)

SELECT a.APNT_NO, c.PT_NAME, a.PT_NO, a.MCDP_CD, b.DR_NAME, a.APNT_YMD
FROM APRIL_APPOINTMENT as a
JOIN DOCTOR as b ON a.MDDR_ID = b.DR_ID
JOIN PATIENT as c ON a.PT_NO = c.PT_NO
ORDER BY a.APNT_YMD asc