SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO
WHERE ITEM_ID IN (
    SELECT A.ITEM_ID
    FROM ITEM_TREE AS A
    JOIN ITEM_INFO AS B ON A.PARENT_ITEM_ID = B.ITEM_ID
    WHERE B.RARITY = 'RARE'
)
ORDER BY ITEM_ID DESC;
