-- 코드를 입력하세요
SELECT DISTINCT(cc.CAR_ID) FROM CAR_RENTAL_COMPANY_CAR as cc
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY as rh ON cc.CAR_ID = rh.CAR_ID
WHERE cc.CAR_TYPE="세단" and rh.START_DATE like "2022-10%"
ORDER BY cc.CAR_ID DESC