-- 코드를 입력하세요
SELECT gb.BOARD_ID, gb.WRITER_ID, gb.TITLE, gb.PRICE, 
CASE WHEN STATUS = 'SALE' THEN '판매중'
WHEN STATUS = 'RESERVED' THEN '예약중'
ELSE '거래완료'
END as STATUS
FROM USED_GOODS_BOARD as gb
WHERE gb.CREATED_DATE LIKE "2022-10-05"
ORDER BY BOARD_ID DESC