-- 코드를 입력하세요
SELECT CONCAT('/home/grep/src/', bo.BOARD_ID, '/', fi.FILE_ID, fi.FILE_NAME, fi.FILE_EXT) as FILE_PATH 
FROM USED_GOODS_BOARD as bo
JOIN USED_GOODS_FILE as fi ON bo.BOARD_ID = fi.BOARD_ID
WHERE VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)
ORDER BY FILE_ID DESC